### ISSUE TITLE
[Request] vpnc

### ISSUE THREAD

**Issue by maddie** [zyxmon/entware-arm#12]
I see that vpnc-scripts package is available in the feed, however I can't find vpnc package in it. I believe it is available in MIPSEL Entware.

Is it possible to include it into Entware-ARM?

Thanks!

**Comment by zyxmon** [comment]
https://dev.openwrt.org/ticket/18221
vpnc package is not mantained by openwrt.
vpnc-scripts can be used with

```
root@ws880:/tmp/home/root# opkg list | grep vpnc
vpnc-scripts - 20150116-1 - This package contains the vpnc-script which is used by vpnc and OpenConnect to configure the tunnel interface.
root@ws880:/tmp/home/root# opkg list | grep openconnect
openconnect - 7.05-1 - A VPN client compatible with Cisco's AnyConnect SSL VPN and ocserv.  OpenConnect is a client that follows the Cisco's AnyConnect SSL VPN protocol, which is supported by IOS 12.4(9)T or later on Cisco SR500, 870, 880, 1800,  2800, 3800, 7200 Series and Cisco 7301 Routers, as well as the OpenConnect VPN server.
```

I'll have a look at vpnc - weather it can be compiled later.

**Comment by maddie** [comment]
Thanks for your quick response!

It would be nice to be able to use vpnc on the router :)

**Comment by zyxmon** [comment]
vpnc is now in the repository

**Comment by maddie** [comment]
Thanks a lot!
