### ISSUE TITLE
The N2N armv7 version doesn't work. No error no message no succeed.

### ISSUE THREAD

**Issue by fordiy** [zyxmon/entware-arm#13]
I run the opkg install n2n. It installed and have two files to /opt/sbin. One is edge and other is supernode. Both two are NOT work on N18U router(Tomato or Asuswrt-Merlin).

No error, no prompt, no any message and quit when I run them. What's wrong?

It download from:
Downloading http://qnapware.zyxmon.org/binaries-armv7/n2n_2.1.0-r7223-1_armv7soft.ipk.

**Comment by zyxmon** [comment]
> > It download from

Downloaded packages will not work. They must be installed with opkg command.
I'm closing the ticket because you've started it in mipsel feed.

**Comment by fordiy** [comment]
I run the opkg install n2n， not just download package to run. where is arm feed?

**Comment by zyxmon** [comment]
I have already adviced you to load tun module. You have not done it.

**Comment by fordiy** [comment]
admin@RT-N18U:/tmp/opt# insmod tun
insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/drivers/net/tun.ko': File exists

It seems files already there. How to load tun module ?

**Comment by zyxmon** [comment]
Please report bugs here. Use forums to ask questions.

**Comment by fordiy** [comment]
admin@RT-N18U:/tmp/opt# modprobe tun
admin@RT-N18U:/tmp/opt#

above I try to check tun is it there, but just return to the # prompt. no error no message not work.
