### ISSUE TITLE
opkg install n2n, after installed n2n not work. no error no message. Please check.

### ISSUE THREAD

**Issue by fordiy** [zyxmon/entware-arm#14]
I run the opkg install n2n from entware-arm. It can be installed and have two files to /opt/sbin. One is edge and other is supernode. Both two are NOT work in N18U router(Tomato or Asuswrt-Merlin).

No error, no prompt, no any message and quit when I run them. What's wrong?

**Comment by fordiy** [comment]
admin@RT-N18U:/tmp/opt# insmod tun
insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/drivers/net/tun.ko': File exists

admin@RT-N18U:/tmp/opt# modprobe tun
admin@RT-N18U:/tmp/opt#

above I try to check tun is it there, but just return to the # prompt. no error no message not work.

**Comment by zyxmon** [comment]
Closing. No response for a long time.
