### ISSUE TITLE
Problem with binary res_fax.so

### ISSUE THREAD

**Issue by the-darkvoid** [zyxmon/entware-arm#16]
When installing Asterisk 11 res_fax.so from the binary entware repository,  http://qnapware.zyxmon.org/binaries-armv7/, the module does not load because of a binding error with the asterisk core application.

Rebuilding both res_fax.so and res_fax_spandsp.so from the git source and installing the resulting packages results in the modules loading fine in Asterisk.

**Comment by zyxmon** [comment]
Please post Makefile you've used to build res_fax.so and res_fax_spandsp.so.

**Comment by the-darkvoid** [comment]
Well it builds fine out of the box with the latest git source. I made no changes to any files, just ran "make" in entware and "make package/compile" in openwrt_trunk.

Just the binary on your published feed seems to have an issue.

**Comment by zyxmon** [comment]
Does the new August build has this issue?

**Comment by zyxmon** [comment]
No response - closing.
