### ISSUE TITLE
urlsnarf - dsniff package

### ISSUE THREAD

**Issue by jerrm** [zyxmon/entware-arm#17]
urlsnarf doesn't work under ARM.  

This is on Tomato Shibby 130.

Program loads and according to syslog places appropriate interface in promiscuous mode, but no traffic is logged.

**Comment by zyxmon** [comment]
May be it works on some other devices/firmwares. It does not show any activity on ws880 running tomato 130_2.
tcpdump works. If someone finds out how to fix the issue - please open the ticket and comment.

**Comment by zyxmon** [comment]
I have checked dsniff on my tomato router. it works only with -c flag. As it is stated in dsniff documentation  "The *snarf tools do not yet support this mode of operation."

**Comment by jerrm** [comment]
I don't know if it will help, but Shibby's optware based package works under ARM. Link:http://tomato.groov.pl/repo-arm/

Entware works under MIPS.

**Comment by zyxmon** [comment]
urlsnarf does not work on asus rt-56u with the latest Entware installed.
