### ISSUE TITLE
r/libtorrent 0.9.6/0.13.6 

### ISSUE THREAD

**Issue by Luckyshark** [zyxmon/entware-arm#18]
Hello,
Do you make a updatet easy install script to r/libtorrent 0.9.6/0.13.6 ? the old Version is 0.9.4/0.13.4
for entware.arm Router i have a ASUS RT-AC87U with Merlin Firmware

Thanks for Answer

**Comment by zyxmon** [comment]
There is package `rtorrent-easy-install`. Please use issues section of github for bug reports and new features (packages) request.

**Comment by Luckyshark** [comment]
oh Sorry i can not find something and my englsich is not good enough thank you
