### ISSUE TITLE
ARM Hard Float?

### ISSUE THREAD

**Issue by southwolf** [zyxmon/entware-arm#19]
Hello zyxmon, how can I config for ARM hard float platform? Thank you!

**Comment by zyxmon** [comment]
A new project is started - https://github.com/Entware-ng/
It is now beta. The defaults will be changed.
But you can test it now and switch to hardfloat. I am away from my home to give you more details.
You must turn off softfloat in `make menuconfig` and modify target or add -mfpu=xxx compiler flags
