### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by LeeWiu** [zyxmon/entware-arm#2]
After first reboot I get:

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

I didn't change anything.
This happen when entering/exiting chrooted debian, I wonder how come I didn't get this on optware-debian or entware.mipsel debian.
I found a temporary solution, to reconfigure locales in debian with:

```
apt-get install locales
dpkg-reconfigure locales
```

and choose en_US.UTF-8

**Comment by zyxmon** [comment]
My guess is: there is no locale in original firmware. /bin/bash (uclibc) complains it cannot find it. Is there a way in asuswrt to set /opt/bin/bash as a shell (bash must be installed).

**Comment by zyxmon** [comment]
> > I found a temporary solution, to reconfigure locales in debian with....

This is a normal solution. The locale is set in /opt/etc/profile file called from /etc/profile after Entware.arm was installed. There was no locale set in the system before Entware.arm was installed.

**Comment by LeeWiu** [comment]
I uploaded another debian version with locales :), all fine now https://www.asuswrt.eu/how-to-install-debian-wheezy-arm/
