### ISSUE TITLE
Strongswan kernel-netlink missing

### ISSUE THREAD

**Issue by ghost** [zyxmon/entware-arm#20]
Hi,

I'm trying to set up strongswan on shibyy's tomato. The package strongswan-mod-kernel-netlink is missing. buildroot/.config has the line (#4439):
# CONFIG_PACKAGE_strongswan-mod-kernel-netlink is not set
I may be wrong but I think this is needed.

**Comment by zyxmon** [comment]
Done in entware-ng
https://github.com/Entware-ng
