### ISSUE TITLE
please add php extensions imap and spelling one and phar

### ISSUE THREAD

**Issue by nobutyeahbutno** [zyxmon/entware-arm#22]
Can you please add these extensions to the php build for entware arm

PHP IMAP extension — Required for mail fetching for osTicket Support System :)
PHP Phar extension — recommended for plugins and language packs for osTicket Support System :)
PHP PSPELL extension - for spelling error checking in roundcube webmail :)

These extensions would be very much appreciated. Also if possible is an upgrade to php 6 able to be done by any chance :)

**Comment by zyxmon** [comment]
please upgrade to entware-ng
