### ISSUE TITLE
Openwrt Printing Packages

### ISSUE THREAD

**Issue by ghost** [zyxmon/entware-arm#4]
Hello Zyxmon,

I know I've been bugging you about cups pdf printing with your Entware-ARM packages. But I found this GIT repo that might make things a whole lot easier. Please take a look at the link below. What do you think about this, will it help make porting a little less complicated?

https://github.com/FranciscoBorges/openwrt-printing-packages 

Thanks again for all your work with these ARM packages.

-Mrengles aka Robert

**Comment by zyxmon** [comment]
I know about these packages - https://github.com/Entware/entware/issues/128#issuecomment-78074389

**Comment by zyxmon** [comment]
Closing for now.
If anybody adopts and tests printing packages - please let me know.
