### ISSUE TITLE
miniupnpd Package

### ISSUE THREAD

**Issue by maforshaw** [zyxmon/entware-arm#8]
I'm trying to compile the miniupnpd package, which isn't included in your pre-built packages, as follows:

make package/feeds/routing/miniupnpd/compile

However, I'm having some trouble with the dependent packages. I was able to fix "package/libs/libnfnetlink/Makefile" by changing all instances of "/usr" to "/opt" but I'm stuck on the iptables package even after making a similar change to "package/network/utils/iptables".

The error I get is:

libxt_layer7.c:25:39: fatal error: linux/netfilter/xt_layer7.h: No such file or directory

Any idea how to fix this, please?

**Comment by zyxmon** [comment]
1. remove references to kernel.mk in all used Makefile's
2. Probably you'll need to add something like TARGET_CFLAGS += -I$(LINUX_DIR)/include
3. Entware.arm uses vanilla kernel 2.6.36. You can try to compile old version of iptables (backfire??) from openwrt when 2.6. kernels were used.
4. I am not sure you will succeed in running miniupnpd after compilation.

**Comment by maforshaw** [comment]
Thank you, I will give it a try.

**Comment by zyxmon** [comment]
iptables from trunk is not difficult to compile.
If somebody wants to test miniupnpd in entware - please contact me.
