### ISSUE TITLE
[REQUEST] Zerotier

### ISSUE THREAD

**Issue by 2senel** [zyxmon/entware-arm#9]
Hi, I was sent here to ask for help.

Can somebody please compile Zerotier for me for Asus AC56U?

https://github.com/zerotier/ZeroTierOne

Thanks!

**Comment by zyxmon** [comment]
Please check - http://qnapware.zyxmon.org/binaries-armv7/test/zerotier_1.0.2-5_armv7soft.ipk
No startup script is provided.
Waiting for your report.

**Comment by 2senel** [comment]
Thank you!

Zt seems to be installed fine. However, when I try to launch it I get:

admin@RT-AC56U:/tmp/mnt/sda1/entware.arm/bin# zerotier-one &
-sh: zerotier-one: not found

Same with zerotier-cli and zerotier-idtool

**Comment by zyxmon** [comment]
# Fixed it. Please reinstall

root@ws880:/opt/bin# ./zerotier-one --help
ZeroTier One version 1.0.2
(c)2011-2014 ZeroTier Networks LLC
Licensed under the GNU General Public License v3

Auto-updates not enabled on this build. You must update manually.

Usage: ./zerotier-one [-switches] [home directory] [-q <query>]

Available switches:
  -h                - Display this help
  -v                - Show version
  -j <networkid>    - join network on startup
  -p <port>         - Port for UDP (default: 9993)
  -t <port>         - Port for TCP (default: disabled)
  -d                - Fork and run as daemon (Unix-ish OSes)
  -q                - Send a query to a running service (zerotier-cli)
  -i                - Generate and manage identities (zerotier-idtool)

#

**Comment by 2senel** [comment]
Works fine, once more, thank you!

**Comment by zyxmon** [comment]
Can you provide an entware style startup script for Zerotier?

**Comment by 2senel** [comment]
Sure, I'll look into it this weekend.

**Comment by zyxmon** [comment]
@ryzhovau
If you will move it to Entware (mips) do not forget to use LDFLAGS
